### ISSUE TITLE
ControlPersist can break edeliver

### ISSUE THREAD

**Issue by aaronjensen** [edeliver/edeliver#104]
If you use `ControlPersist` in your `.ssh/config` such as:

```
Host *
  ControlMaster auto
  ControlPath /tmp/%r@%h:%p
  ControlPersist 1h
```

And you were previously connected to the `RELEASE_STORE` host without agent forwarding enabled on that host, then edeliver will use that connection which, without agent forwarding, could fail.

Adding `-Snone` to all of the ssh commands that rely on agent forwarding should alleviate this.

**Comment by bharendt** [comment]
Another option would be to always enable agent forwarding in the ssh config for the release store host like this:

```
Host your.release-store.host.com
  ForwardAgent yes
  ControlMaster auto
  ControlPath /tmp/%r@%h:%p
  ControlPersist 1h
```

I think it would be better to not disable connection sharing because it can speed up the deployment- and especially the build process. I was not familiar with that option and never used it before, but I think it might be very useful for building. In a quick test builing was about 20 to 30 percent faster using the `ControlMaster` option for the buildhost. So thanks for the hint! 
I will add it to the ["Build releases faster" wiki page](https://github.com/boldpoker/edeliver/wiki/Faster-builds) and we could maybe use it as default for the build commands by passing it as `-o ControlMaster=auto -o ControlPath=/tmp/edeliver-build-host -o ControlPersist 10m` options to the ssh commands.

**Comment by aaronjensen** [comment]
> Another option would be to always enable agent forwarding in the ssh config for the release store host like this:

I would not recommend this. There are [security risks associated with agent forwarding](https://heipei.github.io/2015/02/26/SSH-Agent-Forwarding-considered-harmful/) and control persist only exacerbates those. 

I know that it can speed up deployment, which is why I had it enabled in the first place, but because of agent forwarding security issues I'd be hesitant to do it automatically. I could see making it optional, and then, as you stated, setting `ControlPath` explicitly so that you wouldn't end up getting an existing connection that didn't have agent forwarding enabled.
