### ISSUE TITLE
mix run w/ edeliver

### ISSUE THREAD

**Issue by kyledecot** [edeliver/edeliver#116]
Is it possible to execute something like `mix run priv/repo/seeds.exs` using edeliver? If not what would be the suggested way of seeding the database after a deploy?

**Comment by bharendt** [comment]
Do you mean for the initial deploy? Does `mix edeliver migrate` work to setup the database initially? `mix run priv/repo/seeds.exs` would not work because `mix` is not available in a release.

**Comment by kyledecot** [comment]
Well `mix edeliver migrate` sets up the structure of my database but as for loading the initial data I'm a little confused on how to get that in there. I suppose I could make a module a invoke it from a remote console or something. Since `mix` isn't available in a release do you know how migrations work by chance @bharendt ?

**Comment by bharendt** [comment]
To be able to run the seed `.exs` file containing plain (not compiled) elixir code, you must do mainly two things. Ensure that it is included into the release and evaluate the code on the node. The first should be done automatically as long as the file is in the `priv` dir. The second can be done by executing code on your node which evaluates the file the same way as the [`mix run` task does](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/run.ex#L71): `Code.require_file(file)`. You can find your file at `:code.priv_dir(:your_app) |> Path.join("repo/seeds.exs")` on the node. So you could connect to your node using `bin/your_app remote_console` and type something like:

```elixir
 :code.priv_dir(:your_app) |> Path.join("repo/seeds.exs") |> Code.require_file()
```
to run the seeds file. 

I am not sure whether it makes sense to add this as an exported function to your project which could be executed as rpc call on the node or whether it would make sense to add such a functionality to edeliver because - if I understand right - this needs to be done only once when you start to develop a new application and deploy your very first version of it.

**Comment by kyledecot** [comment]
Well when I would write rails applications a lot of times I would do something like `User.where(...).first_or_create` and I would run my seeds file on each deploy. This would be useful for adding new records to internal models that I didn't want to create UIs for. I suppose I could write a migration for each one of these. 

I agree with you though that I don't know if this should be baked into edeliver. 

Maybe others have thoughts on this?

**Comment by Moxide** [comment]
Hello,
I just used your code to make an initial seed a production release. It worked, but I had to replace "Code.require_file()" with "Code.eval_file()". "require_file" would just freeze the console, no error shown !
Thanks for the tip ;-)

**Comment by lessless** [comment]
Ability to run `exs` scripts will be generally a good feature to have.

**Comment by ryanwinchester** [comment]
Being able to use the commands you can add in distillery would be very helpful.

https://hexdocs.pm/distillery/running-migrations.html#content
