### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by bharendt** [edeliver/edeliver#121]
This would / could include:
- [ ] **Build in local docker container**
  - [ ] specify docker image in config instead of build host
  - [ ] allow to build docker image before building the release. requires to configure the docker file to use.
  - [ ] start docker container
  - [ ] convert ssh build commands to docker `exec` commands
  - [ ] convert copy commands to docker `exec` or docker `cp` commands, e.g. to copy old release when building upgrades
  - [ ] copy release tar from docker container to release store
  - [ ] stop container (also when build is canceled)
- [ ] **Update release in docker image after build**
  - [ ] copy release tar from build container to deploy container
  - [ ] add tag(s), maybe from auto-versioning
  - [ ] push that image (and tags)

Extras: 
- [ ] Execute fixed hook from config for `deploy release` command which deploys the container instead of the release
- [ ] Cache build dir on local machine (store after current build and restore before next build) to make `GIT_CLEAN_PATHS` and `SKIP_GIT_CLEAN` behave the same as on a remote build host
  - [ ] allow to configure cache-dir (e.g. for CI)
  - [ ] copy project dir to cache-dir instead of container
  - [ ] run git clean using `GIT_CLEAN_PATHS` config there
  - [ ] copy to build container
  - [ ] copy from build container after successful or canceled build

**Comment by Linuus** [comment]
Yes! It would be great to be able to use a Docker container instead of a dedicated build host!

**Comment by yagooar** [comment]
Is anybody working on this task? I would happily help with this.

**Comment by luckynum7** [comment]
Hi guys,

I'm trying to use a docker image for edeliver now, for the "hot code reload" is cool. 👍 

Speaking of build with docker, I've used [edib](https://github.com/edib-tool/mix-edib) (elixir docker image builder). Which can build a small docker image (alpine).
In short, it starts a docker container and build the release into a tarball, and then use the tarball to build a docker image.

**Comment by mk** [comment]
@yagooar would love to get help on this. Unfortunately we're not able to invest much time into edeliver at the moment so any help is much appreciated. Also if anyone wants to help with maintaining we're more than happy to give commit rights and provide guidance.

**Comment by accordeiro** [comment]
Hi @mk – when I first used edeliver, this was a feature that I really missed, so I'd be happy to work on it :)

**Comment by mk** [comment]
@accordeiro that was quick! Sent out an invite to the edeliver org. Do you need any help getting started?

**Comment by accordeiro** [comment]
@mk awesome, thanks! I'll probably have some questions regarding project structure (to make sure I put things in the right place) once I get started tonight – I'll let you know as soon as anything comes up. How does that sound?

Btw, do you have any contributor's guide?

**Comment by ellispritchard** [comment]
Hi; I had trouble with some of the existing "Elixir Docker" build images producing huge images, so rolled my own.

Consists of: 

https://github.com/Financial-Times/docker-elixir-build - the 'build server' image: it relies on mounts (`/project` and `/release`) from the host machine for the input (source) and output (release) files, and builds in Elixir and Erlang.

I then have a Mix task that co-ordinates the build process:

https://gist.github.com/ellispritchard/fcd15c97be4f83ec66e7d74c6a8793e3

The Mix task uses a little bash script to build and release the project (Gist `rel-slash-docker-build.sh` AKA `rel/docker-build.sh`) inside the Docker image (I could have put this in the build image for less flexibility!), with the build artefacts going into the host-mounted `/release` dir.

(The asset packaging is done by the Mix task outside of Docker, since the output (the JS and CSS) is binary independent, so seemed to be little point in doing it in the build container).

Once the build container has built the release into the imported `/release` directory (using distillery), the Mix task builds the application Docker image (Gist`rel-slash-Dockerfile` AKA `rel/Dockerfile`), which just copies the release from the `/release` directory into the image, straight on-top of the base Alpine image, and sets up the `CMD` to runs the application. 

My Phoenix + Absinthe images come out ~50MB larger than the base Alpine image (~53MB altogether), which I'm very happy with. 

It also means you don't have a stack of images to update whenever you want to update the base Alpine image.

Feel free to 'derive' from this if it saves some work.

**Comment by ellispritchard** [comment]
Now Docker 17.06 is out, multi-stage builds are available, which makes all this so much simpler:

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by accordeiro** [comment]
That's very helpful, thanks @ellispritchard 👍

**Comment by ellispritchard** [comment]
See https://github.com/Financial-Times/docker-elixir-build for details of multi-stage Docker build for Elixir. 😄

**Comment by AlexRiedler** [comment]
based off @ellispritchard I have produced something that is very similar that works pretty well.

Build Project:
`docker build --no-cache --target build -t my_project:build .`

This will produce something like:
`/build/_build/prod/rel/my_project/releases/0.0.1/my_project.tar.gz` in the container

which can be copied out via:

```
docker container create --name extract my_project:build  
docker container cp extract:/build/_build/prod/rel/my_project/releases/0.0.1/my_project.tar.gz .deliver/releases/my_project.tar.gz  
docker container rm -f extract
```

or you can build and make a docker image for release simply by:

`docker build --no-cache --target release -t my_project:release .`

I think this would support both the use case of doing hot reload upgrades as well (if your production environment is not a docker environment).

The thing that would be very different however is that the current edeliver process uses git to git pull from your localhost + git cleans which this obviously doesn't. This would also need updated to handle filenames for releases.

My Phoenix Base Project: https://github.com/AlexRiedler/my_project

**Comment by inooid** [comment]
I am currently looking into this. Is this still relevant to pick up?
