### ISSUE TITLE
Support for ssh agent forwarding 

### ISSUE THREAD

**Issue by lbrito1** [edeliver/edeliver#231]
I have a build host that can access a staging host through ssh agent forwarding. Thus, I have to ssh into  staging without specifying a username, as so: `ssh mystaginghost`. However, eDeliver doesn't allow blank or empty `STAGING_USER`. The `username@hostname` string seems hardcoded in some places, so an empty username would just result in an incorrect connection string.

Is there some option that allows forwarding the agent to target (staging/prod) hosts without a username?
### Current behavior

When providing no or blank STAGING_USER and running `mix edeliver deploy release to staging --verbose`:

```
EDELIVER IS MISSING THE FOLLOWING CONFIG(S):

STAGING_USER
```

### Expected behavior

Allow user to provide no or blank STAGING_USER and forward the ssh agent to target host.

**Comment by onelesd** [comment]
I'm not sure I fully understand your problem, but since no one has chimed in I'll provide what works for me.

The ssh client (w/ or w/o agent forwarding) is using a username, even when you don't specify one. When not specified it is the current user. Typically you would create an `edeliver` user on build/staging/production, and add ssh keys on the deploy hosts. In that case, your STAGING_USER would be "edeliver".

The only place agent forwarding comes in is to forward your local keys for the github repo access during the build process. You would enable that in your ssh config: `ForwardAgent yes`.

HTH

**Comment by lessless** [comment]
Thanks @onelesd 

@lbrito1  does it resolve your issue?

**Comment by lbrito1** [comment]
tbh its been a while since I last did anything with Elixir, @lessless. Since this is not an issue anymore for me, I'm going to close this.

**Comment by lessless** [comment]
Thanks!
