### ISSUE TITLE
Building locally?

### ISSUE THREAD

**Issue by hopewise** [edeliver/edeliver#244]
How would I build locally on my ubuntu?
I have:

     edeliver v1.4.4 | https://github.com/boldpoker/edeliver

When I run: 

     mix edeliver build release --branch=master
I get:

```
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
ssh: connect to host localhost port 22: Connection refused

A remote command failed on:

  ubuntu@localhost

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 255:

    set -e
    if [ ! -d /home/ubuntu/Documents/projects/elixir/tmp/edeliver/trackware/builds ]
    then
      mkdir -p /home/ubuntu/Documents/projects/elixir/tmp/edeliver/trackware/builds
      cd /home/ubuntu/Documents/projects/elixir/tmp/edeliver/trackware/builds
      git init &> /dev/null
      git config receive.denyCurrentBranch ignore
    else
      cd /home/ubuntu/Documents/projects/elixir/tmp/edeliver/trackware/builds
      git config receive.denyCurrentBranch ignore
    fi

```

**Comment by PanfilovDenis** [comment]
+1

**Comment by geonnave** [comment]
Today I had this need, and I solved it by just configuring local build (`BUILD_HOST="localhost"`).

Note that you must have a ssh server set up on your local machine (see http://ubuntuhandbook.org/index.php/2016/04/enable-ssh-ubuntu-16-04-lts/)

Also, do not forget to add your own key to ~/.ssh/authorized_keys, in order to enable passwordless login (see https://stackoverflow.com/a/16651742/2660817)

**Comment by lessless** [comment]
Thanks @geonnave
